version: 1

formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

handlers:
  api_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: /home/jovyan/logs/api/adzuna_api.log
    maxBytes: 10485760   
    backupCount: 5

  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard

loggers:
  api:
    level: INFO
    handlers: [api_file, console]
    propagate: false

root:
  level: WARNING
  handlers: [console]
